name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: ./mvcdocker
    - name: Publish Docker Action
      uses: jerray/publish-docker-action@v1.0.3
      with:
        username: yaqi0714
        # Password used to login docker registry
        password: Lyq=890714
        # Docker registry server address
        registry: docker.io
        # Docker file used to build image
        file: ./mvcdocker/mvcdocker/Dockerfile
        # Docker build context
        path: ./mvcdocker # optional, default is .
        # Static image tag list, separated by comma
        tags: yaqi0714/mvcdocker:latest # optional, default is latest
        # Docker build-time variables, separated by comma
        #build_args: build . -f ./mvcdocker/dockerfile# optional
        # If allow pull request trigger build
        allow_pull_request: true # optional
        # Generate tags by conditions automatically
        #auto_tag: # optional
        # Images to consider as cache sources
        #cache: # optional
