name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Build & Push
      uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
        image: yaqi0714/mvcdocker
        tag: latest
        registry: docker.io
        dockerfile: ./mvcdocker/Dockerfile
        username: yaqi0714
        password: Lyq=890714
