name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
      with:
        # Version to use. E.g. 2.2.104
        version: 2.2.104 # optional
    - name: Checkout
      uses: actions/checkout@v1
    - uses: ./
    - name: Docker Action
      uses: zenato/docker-action@v1.0.0
      with:
        # Registry username
        username: yaqi0714
        # Registry password
        password: Lyq=890714
        # Repository on registry
        repository: yaqi0714/mvcdocker
        # Registry hostname
        registry: docker.io # optional
        # Image tag
        tag: latest # optional
