name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: ./
    - name: Docker Build & Push
      uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
        # Name of the Docker image
        image: yaqi0714/mvcdocker
        # Tag override for Docker image
        tag: latest # optional
        # Target Docker registry
        registry: docker.io
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: Dockerfile # optional, default is Dockerfile
        # Docker registry username
        username: yaqi0714 # optional
        # Docker registry password
        password: Lyq=890714 # optional
